---

- name: apt | ensure apt-transport-https and gpg are present
  apt:
    name: [apt-transport-https, gpg]
    state: present

- name: add falcosecurity key
  apt_key:
    url: https://falco.org/repo/falcosecurity-3672BA8F.asc
    state: present
  register: pkg_result
  until: pkg_result is success

- name: install falcosecurity apt source
  vars:
    pkg_name: "{{'deb-dev' if (falco_dev) else 'deb'}}"
  apt_repository:
    repo: "deb https://dl.bintray.com/falcosecurity/{{ pkg_name }} stable main"
    filename: falcosecurity
    mode: 0444
    state: present

## to ensure gcc available for dkms
- include: gcc.yml

- name: apt | kernel headers install
  apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present
  ignore_errors: true
  register: pkg_result
  until: pkg_result is success

- name: apt | falco install
  apt:
    name: "{{ falco_pkgs }}"
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success
