---

- name: yum | install falcosecurity repository key
  rpm_key:
    state: present
    key: https://falco.org/repo/falcosecurity-3672BA8F.asc
  register: pkg_result
  until: pkg_result is success

- name: yum | install falcosecurity repository
  vars:
    repo_name: "{{'falcosecurity-rpm-dev.repo' if (falco_dev) else 'falcosecurity-rpm.repo'}}"
  get_url:
    url: "https://falco.org/repo/{{ repo_name }}"
    dest: /etc/yum.repos.d/falcosecurity.repo
    mode: 0644

- name: yum | kernel-devel install
  yum:
    name: "kernel-devel-{{ ansible_kernel }}"
    state: present
    update_cache: yes
  ignore_errors: true
  register: pkg_result
  until: pkg_result is success

- name: yum | falco install
  yum:
    name: "{{ falco_pkgs }}"
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success
